# Generated by Django 4.2.7 on 2024-04-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент лекции', 'verbose_name_plural': 'Контент лекций'},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='string_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='italic_words',
        ),
        migrations.RemoveField(
            model_name='content',
            name='uppercase_words',
        ),
        migrations.AddField(
            model_name='content',
            name='content_number',
            field=models.IntegerField(default=None, verbose_name='Номер абзаца'),
        ),
    ]
