# Generated by Django 4.2.7 on 2024-04-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0003_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='URL'),
        ),
    ]
