# Generated by Django 4.2.7 on 2024-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0004_specialization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=4000, verbose_name='Абзац')),
                ('paragraph_number', models.IntegerField(default=None, verbose_name='Номер абзаца')),
            ],
            options={
                'verbose_name': 'Контент лекции',
                'verbose_name_plural': 'Контент лекций',
            },
        ),
        migrations.AlterField(
            model_name='lection',
            name='lection_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название лекции'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='lection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lections.lection', verbose_name='Лекция'),
        ),
    ]
