# Generated by Django 4.2.7 on 2024-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0005_paragraph_alter_lection_lection_name_delete_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.TextField(max_length=10000, verbose_name='Абзац'),
        ),
    ]
