# Generated by Django 4.2.7 on 2024-04-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0006_alter_paragraph_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
    ]
