# Generated by Django 4.2.7 on 2024-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0008_lectionimage_lectionaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='in_production',
            field=models.BooleanField(default=False, verbose_name='Готовность лекции'),
        ),
    ]
