# Generated by Django 4.2.7 on 2024-05-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0010_remove_lectionimage_paragraph_id_delete_lectionaudio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together={('lection_id', 'paragraph_number')},
        ),
    ]
