# Generated by Django 4.2.7 on 2024-05-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0014_adminlectionaction_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together=set(),
        ),
    ]
