# Generated by Django 4.2.7 on 2024-06-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0016_alter_paragraph_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together=set(),
        ),
    ]
