# Generated by Django 4.2.7 on 2024-06-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0017_alter_paragraph_unique_together'),
        ('materials', '0004_alter_audio_audio_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Аудиозапись', 'verbose_name_plural': 'Аудиозаписи в базе данных'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения в базе данных'},
        ),
        migrations.AlterModelOptions(
            name='lectionaudio',
            options={'verbose_name': 'Аудиозапись', 'verbose_name_plural': 'Аудиозаписи в лекциях'},
        ),
        migrations.AlterModelOptions(
            name='lectionimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения в лекциях'},
        ),
        migrations.AlterField(
            model_name='lectionimage',
            name='paragraph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lections.paragraph', verbose_name='Параграф'),
        ),
    ]
