# Generated by Django 4.2.7 on 2024-06-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0017_alter_paragraph_unique_together'),
        ('materials', '0005_alter_audio_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectionimage',
            name='paragraph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_id', to='lections.paragraph', verbose_name='Параграф'),
        ),
    ]
