# Generated by Django 4.2.7 on 2024-06-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_lectionimage_paragraph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectionimage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='materials.image', verbose_name='Изображение'),
        ),
    ]
