# Generated by Django 4.2.7 on 2024-06-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0017_alter_paragraph_unique_together'),
        ('materials', '0007_alter_lectionimage_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectionaudio',
            name='paragraph_id',
        ),
        migrations.RemoveField(
            model_name='lectionimage',
            name='paragraph_id',
        ),
        migrations.AddField(
            model_name='lectionaudio',
            name='lection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lections.lection', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='lectionaudio',
            name='position',
            field=models.IntegerField(default=None, verbose_name='Номер абзаца'),
        ),
        migrations.AddField(
            model_name='lectionimage',
            name='lection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lections.lection', verbose_name='Лекция'),
        ),
        migrations.AddField(
            model_name='lectionimage',
            name='position',
            field=models.IntegerField(default=None, verbose_name='Номер абзаца'),
        ),
        migrations.AlterField(
            model_name='lectionimage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.image', verbose_name='Изображение'),
        ),
    ]
