# Generated by Django 4.2.7 on 2024-06-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0017_alter_paragraph_unique_together'),
        ('materials', '0008_remove_lectionaudio_paragraph_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectionaudio',
            unique_together={('lection_id', 'audio_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='lectionimage',
            unique_together={('lection_id', 'image_id', 'position')},
        ),
    ]
