# Generated by Django 4.2.7 on 2024-06-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_lectionaudio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectionaudio',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lectionimage',
            unique_together=set(),
        ),
    ]
