# Generated by Django 4.2.7 on 2024-06-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0017_alter_paragraph_unique_together'),
        ('materials', '0010_alter_lectionaudio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectionaudio',
            name='position',
        ),
        migrations.RemoveField(
            model_name='lectionimage',
            name='position',
        ),
        migrations.AddField(
            model_name='lectionaudio',
            name='paragraph_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lections.paragraph', verbose_name='Параграф лекции'),
        ),
        migrations.AddField(
            model_name='lectionimage',
            name='paragraph_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lections.paragraph', verbose_name='Параграф лекции'),
        ),
    ]
