# Generated by Django 4.2.7 on 2024-06-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_remove_lectionaudio_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectionaudio',
            name='lection_id',
        ),
        migrations.RemoveField(
            model_name='lectionimage',
            name='lection_id',
        ),
    ]
