# Generated by Django 4.2.7 on 2024-04-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lections', '0007_lection_in_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lection_images', verbose_name='Картинка')),
                ('paragraph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lections.paragraph', verbose_name='ID абзаца лекции')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='lection_audio', verbose_name='Аудиозапись')),
                ('paragraph_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lections.paragraph', verbose_name='ID абзаца лекции')),
            ],
        ),
    ]
