# Generated by Django 4.2.7 on 2024-04-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lections', '0004_specialization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin_in_rus', models.CharField(max_length=100, verbose_name='Термин на русском')),
                ('termin_in_eng', models.CharField(max_length=100, verbose_name='Термин на английском')),
                ('lection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lections.lection', verbose_name='Лекция')),
            ],
            options={
                'verbose_name': 'словарь',
                'verbose_name_plural': 'словари',
            },
        ),
    ]
