# Generated by Django 4.2.7 on 2024-04-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lections', '0007_lection_in_production'),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictionary',
            unique_together={('termin_in_rus', 'termin_in_eng', 'lection_id')},
        ),
    ]
