# Generated by Django 4.2.7 on 2024-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_dictionary_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDictionaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Действие со словарем',
                'verbose_name_plural': 'Действия со словарями',
            },
        ),
    ]
