# Generated by Django 4.2.7 on 2024-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_admindictionaryaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindictionaryaction',
            name='url',
            field=models.CharField(default='#', max_length=50, verbose_name='Ссылка'),
        ),
    ]
